//
//  PSColor.m
//  ProjectSpy
//
//  Created by Dan Clawson on 4/19/15.
//  Copyright (c) 2015 Slacker Tools. All rights reserved.
//

#import "UIColor+PSColor.h"

static CGFloat const StandardTransparency = 1.0;

@interface UIColor ()

@end

@implementation UIColor (PSColor)

#pragma mark - Primary Colors

+ (UIColor *) psPrimary0 {
    return [UIColor colorWithRed:0.667 green:0.439 blue:0.224 alpha:StandardTransparency];
}

+ (UIColor *) psPrimary1 {
    return [UIColor colorWithRed:0.937 green:0.929 blue:0.925 alpha:StandardTransparency];
}

+ (UIColor *) psPrimary2 {
    return [UIColor colorWithRed:0.847 green:0.714 blue:0.588 alpha:StandardTransparency];
}

+ (UIColor *) psPrimary3 {
    return [UIColor colorWithRed:0.486 green:0.239 blue:0 alpha:StandardTransparency];
}

+ (UIColor *) psPrimary4 {
    return [UIColor colorWithRed:0.333 green:0.161 blue:0 alpha:StandardTransparency];
}

#pragma mark - Secondary Colors (1)

+ (UIColor *) psSecondaryOne0 {
    return [UIColor colorWithRed:0.396 green:0.6 blue:0.2 alpha:StandardTransparency];
}

+ (UIColor *) psSecondaryOne1 {
    return [UIColor colorWithRed:0.835 green:0.839 blue:0.831 alpha:StandardTransparency];
}

+ (UIColor *) psSecondaryOne2 {
    return [UIColor colorWithRed:0.639 green:0.757 blue:0.525 alpha:StandardTransparency];
}

+ (UIColor *) psSecondaryOne3 {
    return [UIColor colorWithRed:0.216 green:0.439 blue:0 alpha:StandardTransparency];
}

+ (UIColor *) psSecondaryOne4 {
    return [UIColor colorWithRed:0.145 green:0.298 blue:0 alpha:StandardTransparency];
}

#pragma mark - Secondary Colors (2)

+ (UIColor *) psSecondaryTwo0 {
    return [UIColor colorWithRed:0.588 green:0.196 blue:0.329 alpha:StandardTransparency];
}

+ (UIColor *) psSecondaryTwo1 {
    return [UIColor colorWithRed:0.824 green:0.816 blue:0.82 alpha:StandardTransparency];
}

+ (UIColor *) psSecondaryTwo2 {
    return [UIColor colorWithRed:0.745 green:0.518 blue:0.596 alpha:StandardTransparency];
}

+ (UIColor *) psSecondaryTwo3 {
    return [UIColor colorWithRed:0.431 green:0 blue:0.145 alpha:StandardTransparency];
}

+ (UIColor *) psSecondaryTwo4 {
    return [UIColor colorWithRed:0.294 green:0 blue:0.098 alpha:StandardTransparency];
}

#pragma mark - Complement Colors

+ (UIColor *) psComplement0 {
    return [UIColor colorWithRed:0.145 green:0.369 blue:0.412 alpha:StandardTransparency];
}

+ (UIColor *) psComplement1 {
    return [UIColor colorWithRed:0.145 green:0.208 blue:0.216 alpha:StandardTransparency];
}

+ (UIColor *) psComplement2 {
    return [UIColor colorWithRed:0.153 green:0.263 blue:0.282 alpha:StandardTransparency];
}

+ (UIColor *) psComplement3 {
    return [UIColor colorWithRed:0.082 green:0.467 blue:0.537 alpha:StandardTransparency];
}

+ (UIColor *) psComplement4 {
    return [UIColor colorWithRed:0.016 green:0.482 blue:0.569 alpha:StandardTransparency];
}

/*
 
 #####  Color Palette by Paletton.com
 #####  Palette URL: http://paletton.com/#uid=70y211kllll0ktX9Nr2yDfC+2aDkllllaTbjeWeMrKrUvNtvkllll0ktX9Nr2yDfC+2aDkllll0ktX9Nr2yDfC+2aD
 
 
 *** Primary color:
 
 shade 0 = #AA7039 = rgb(170,112, 57) = rgba(170,112, 57,1) = rgb0(0.667,0.439,0.224)
 shade 1 = #EFEDEC = rgb(239,237,236) = rgba(239,237,236,1) = rgb0(0.937,0.929,0.925)
 shade 2 = #D8B696 = rgb(216,182,150) = rgba(216,182,150,1) = rgb0(0.847,0.714,0.588)
 shade 3 = #7C3D00 = rgb(124, 61,  0) = rgba(124, 61,  0,1) = rgb0(0.486,0.239,0)
 shade 4 = #552900 = rgb( 85, 41,  0) = rgba( 85, 41,  0,1) = rgb0(0.333,0.161,0)
 
 *** Secondary color (1):
 
 shade 0 = #659933 = rgb(101,153, 51) = rgba(101,153, 51,1) = rgb0(0.396,0.6,0.2)
 shade 1 = #D5D6D4 = rgb(213,214,212) = rgba(213,214,212,1) = rgb0(0.835,0.839,0.831)
 shade 2 = #A3C186 = rgb(163,193,134) = rgba(163,193,134,1) = rgb0(0.639,0.757,0.525)
 shade 3 = #377000 = rgb( 55,112,  0) = rgba( 55,112,  0,1) = rgb0(0.216,0.439,0)
 shade 4 = #254C00 = rgb( 37, 76,  0) = rgba( 37, 76,  0,1) = rgb0(0.145,0.298,0)
 
 *** Secondary color (2):
 
 shade 0 = #963254 = rgb(150, 50, 84) = rgba(150, 50, 84,1) = rgb0(0.588,0.196,0.329)
 shade 1 = #D2D0D1 = rgb(210,208,209) = rgba(210,208,209,1) = rgb0(0.824,0.816,0.82)
 shade 2 = #BE8498 = rgb(190,132,152) = rgba(190,132,152,1) = rgb0(0.745,0.518,0.596)
 shade 3 = #6E0025 = rgb(110,  0, 37) = rgba(110,  0, 37,1) = rgb0(0.431,0,0.145)
 shade 4 = #4B0019 = rgb( 75,  0, 25) = rgba( 75,  0, 25,1) = rgb0(0.294,0,0.098)
 
 *** Complement color:
 
 shade 0 = #255E69 = rgb( 37, 94,105) = rgba( 37, 94,105,1) = rgb0(0.145,0.369,0.412)
 shade 1 = #253537 = rgb( 37, 53, 55) = rgba( 37, 53, 55,1) = rgb0(0.145,0.208,0.216)
 shade 2 = #274348 = rgb( 39, 67, 72) = rgba( 39, 67, 72,1) = rgb0(0.153,0.263,0.282)
 shade 3 = #157789 = rgb( 21,119,137) = rgba( 21,119,137,1) = rgb0(0.082,0.467,0.537)
 shade 4 = #047B91 = rgb(  4,123,145) = rgba(  4,123,145,1) = rgb0(0.016,0.482,0.569)
 
 
 #####  Generated by Paletton.com (c) 2002-2014

 */

@end
